services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: network-stability-watchdog-hub
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
